### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by moon6pence** [JuliaGPU/CUDArt.jl#1]
Hi, all. 

I'm trying to run CUDArt.jl in Windows. I feel comfortable to use Julia in linux systems but supporting many platforms is always good thing. Futhermore, my customers in optics lab are Muggle - they are not familiar with programming and linux systems. 

Ok, after long idle talk, it would be simple to make run in Windows - maybe add correct path and name of CUDA runtime and driver DLL. 

For CUDA 5.0 64bit
- CUDA driver API : `C:\Windows\system32\nvcuda.dll`
- CUDA runtime API : `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.0\bin\cudart64_50_35.dll`

Driver API is simple, but DLL name of runtime API is more complicated. I think it have to be checked for several CUDA releases. 

I checked both driver and runtime APIs are loaded properly, rest TODOs are:
- Checked library name of runtime API in other CUDA releases (maybe 4.x, 5.0, 5.5, 6.0 will be enough)
- Build wrapcuda.dll mingw+CUDA environment
- Confirm all testcases are passed. 

I will log progress here, and I wish I can send my first PR to repository soon. Thanks!

**Comment by moon6pence** [comment]
Hello, I'm back. 
I'm sorry that I just threw issue and did nothing yet. 

Recently my work is aim to julia and I have chance to dig up again. 
I hope that there's some updates soon.

**Comment by moon6pence** [comment]
Ah sorry misclicked T_T 

'Close' means close the issue.

**Comment by moon6pence** [comment]
Hello, I'm back. 
I'm sorry that I just threw issue and did nothing yet. 

Recently my work is aim to julia and I have chance to dig up again. 
 I hope that there's some updates soon.

**Comment by timholy** [comment]
That will be great, glad to hear it!

Presumably you know about https://github.com/maxruby/OpenCV.jl, since (if I remember correctly) that was another of your interests.

**Comment by moon6pence** [comment]
Yes, I have been watching mailing lists and very excited to hear that. 

Support OpenCV GPU functions with CudaArray will be another possible issues, too. 
I used to mix CUDA kernels and OpenCV GPU functions while implement image processing algorithms in C++.

**Comment by moon6pence** [comment]
https://github.com/moon6pence/CUDArt.jl/commits/support_windows

It works well with Visual Studio 2013 and CUDA 6.5, involve build.jl. `Pkg.build("CUDArt")`
As I said, visual studio command prompt is required because we cannot use nvcc in mingw. 

I would decide support how many versions of VS (maybe 2010, 2012, 2013) and CUDA.

**Comment by timholy** [comment]
Cool! Certainly one of the things we probably both need to do is make it work for different paths---as you say, it seems especially important not to require a specific version of VS.

But this looks very close, so please do submit as a pull request when you feel ready.
