### ISSUE TITLE
Support various versions of CUDA Toolkit

### ISSUE THREAD

**Issue by moon6pence** [JuliaGPU/CUDArt.jl#11]
Current CUDArt.jl use generated api bindings from CUDA Toolkit 6.5. (`libcudart-6.5.jl` and files in `gen-6.5/`)
And CUDA 5.5 files seems to be not used. (`libcudart-5.0.jl` and files in `gen/`)

I simplely tested current 6.5 api binding with CUDA 5.0/5.5/6.0/6.5 and even **7.0 RC**. 
(Yeah, I want to use boring time in this afternoon to just click install buttons. It is better test in Windows rather than linux.)
By result, current 6.5 binding works well in all those versions because we don't use any special new functions in recent cuda runtimes. 

So my suggestion is:

* Remove api bindings from CUDA 5.0 and keep only latest api binding. 
* Use find_library for libcudart with version 5.0 - 7.0 and we can say CUDArt.jl supports all these versions. 
* If there's new functionality that uses api from certain version of cuda runtime, we have to check the version of installed cuda toolkit. 

How do you think?

**Comment by timholy** [comment]
That seems like a fine plan. I generated the 6.5 bindings because I was debugging a problem, but it turned out to stem from a different source. I'll fix it up on the Linux side, it might need your input to get it working on Windows.

**Comment by moon6pence** [comment]
Thanks! 

These dependency works feel like building such as `FindCUDA.cmake` script in cmake. 
I will also develop features in ubuntu and just check tests in windows.
