### ISSUE TITLE
void * type cuda malloc does not work

### ISSUE THREAD

**Issue by jltmtz** [JuliaGPU/CUDArt.jl#23]
Allocating memory in the GPU works super well for most types. E.g.

```
julia> CUDArt.malloc( Cint, 10 )
CUDArt.CudaPtr{Int32}(Ptr{Int32} @0x00000013047a0000)
```

However, when trying to allocate memory for a void pointer (as e.g., the [CUB](http://nvlabs.github.io/cub/) library requires for some functions), the returned pointer is always 0:

```
julia> CUDArt.malloc( Void, 10 )
CUDArt.CudaPtr{Void}(Ptr{Void} @0x0000000000000000)
```

**Comment by timholy** [comment]
You can figure out why this happens by `@which CUDArt.malloc( Void, 10 )` and then noticing that julia says `sizeof(Void)` is 0. `Void` is the type for `nothing`, and in julia it is literally...nothing.

Your best bet is to allocate with `Int`; using `ccall` I think you should be able to pass a `Ptr{Int}` directly as if it were a `Ptr{Void}`. You can also `convert` them if you want.

**Comment by jltmtz** [comment]
Thanks!, that was exactly my workaround; It only feels a bit awkward to allocate on one type and then convert to the other.

I guess a better way to do this would be to have a `Cvoid` (similar to `Cint`, `Cfloat` and so on) for this use case, but that is probably a discussion better suited for `Julia.base`.

**Comment by timholy** [comment]
Actually, now that I read more carefully you might be asking to allocate an array of `void*`? If so, that's `CUDArt.malloc( Ptr{Void}, 10 )`, which I think does what you want.

**Comment by jltmtz** [comment]
`CUDArt.malloc( Ptr{Void}, 10 )` does the job. Thanks a lot!
