### ISSUE TITLE
warning in julia v0.4

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDArt.jl#24]
I get this with the latest Julia and don't quite know how to fix it as I think gen_libcudart_h.jl is an automatically generated file.
```
WARNING: uint32(x) is deprecated, use UInt32(x) instead.
while loading /home/nlg-05/dy_052/kuparser/profile/v0.4/CUDArt/src/../gen-6.5/gen_libcudart_h.jl, in expression starting on line 41
```

**Comment by timholy** [comment]
Yeah, I'm just living with this until julia 0.4 comes out. It doesn't really hurt anything performance-wise, because it's just defining constants.

**Comment by malmaud** [comment]
I believe this is closed by https://github.com/JuliaGPU/CUDArt.jl/pull/29.

**Comment by timholy** [comment]
Actually by #27, but yeah it can be closed.
