### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pearcemc** [JuliaGPU/CUDArt.jl#32]
Hello

I'm trying to get CUDArt going on a HPC platform (meaning some libraries are in non-standard places). Could anyone shed light on the error below?

julia> using CUDArt
INFO: Precompiling module CUDArt...
ERROR: LoadError: LoadError: Cannot find libwrapcuda
 in error at ./error.jl:21
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:252
 in _start at ./client.jl:375
while loading /home/mcp50/.julia/v0.5/CUDArt/src/libcudart-6.5.jl, in expression starting on line 53
while loading /home/mcp50/.julia/v0.5/CUDArt/src/CUDArt.jl, in expression starting on line 27
ERROR: Failed to precompile CUDArt to /home/mcp50/.julia/lib/v0.5/CUDArt.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:383
 in require at ./loading.jl:250

**Comment by timholy** [comment]
What does `Pkg.build("CUDArt")` say?

**Comment by pearcemc** [comment]
I ended up building everything from source, ensuring all git repos up to date etc and it works now.

**Comment by timholy** [comment]
Great, thanks for letting us know.

**Comment by liusihaoshiwo** [comment]
@pearcemc I have the same problem. Could you please tell me how to build libwrapcuda from the CUDArt source with nvcc?

INFO: Precompiling module CUDArt...
ERROR: LoadError: LoadError: Cannot find libwrapcuda
 in error at error.jl:21
while loading C:\Users\Miller\.julia\v0.4\CUDArt\src\libcudart-6.5.jl, in expression starting on line 53
while loading C:\Users\Miller\.julia\v0.4\CUDArt\src\CUDArt.jl, in expression starting on line 27
Failed to precompile CUDArt to C:\Users\Miller\.julia\lib\v0.4\CUDArt.ji
in error at base\error.jl:21

**Comment by liusihaoshiwo** [comment]
@timholy Thank you for replying me at #48 . It seems that the VS2015 problem was fixed but I met another problem about loading libwrapcuda.

**Comment by timholy** [comment]
Can you paste the output of `Pkg.build("CUDArt")`?

**Comment by liusihaoshiwo** [comment]
Sure, it seems that the problem of VS2015 still exists. But I check the website of NVIDIA. It says that CUDA Toolkits can only be used with VS2013, Could that be the cause of this problem?

ENV["foo"] = "bar"
"bar"
haskey(ENV, "foo")
true
using CUDA
CUDA Driver Initialized
Pkg.build("CUDArt")
INFO: Building CUDArt
===============================[ ERROR: CUDArt ]================================

LoadError: Cannot find proper Visual Studio installation. VS 2013, 2012, or 2010 is required.
while loading C:\Users\Miller\.julia\v0.4\CUDArt\deps\build.jl, in expression starting on line 10

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDArt had build errors.

 - packages with build errors remain installed in C:\Users\Miller\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("CUDArt")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by timholy** [comment]
Until you get past the build error, you shouldn't expect anything else to work.

Sounds like you need VS2013 (but I'm no expert).

**Comment by linuxvictim** [comment]
Put 
_"windows? (
    begin
        if haskey(ENV, "**VS140COMNTOOLS**")
            vs_cmd_prompt = string(ENV["**VS140COMNTOOLS**"], "..\\..\\VC\\vcvarsall.bat")...."_
in _build.jl_  if you have VS2015 installed.
