### ISSUE TITLE
strange splatting bug

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDArt.jl#41]
I am not sure if this bug belongs here or in the base or if I should get my head checked but this got me stumpted.  And it does not happen when I replace CudaArray's with Array's.  So I am posting here:

```
using CUDArt

function bmultest5(a::CudaArray, d::Dims)
    @show typeof(size(a))
    @show size(a)
    b = reinterpret(eltype(a), a, d)
    @show typeof(size(b))
    @show size(b)
    @show Cint[size(b)...]
end

bmultest5(CudaArray(zeros(2)), (2,1,1,1))
```

gives

```
typeof(size(a)) = Tuple{Int64}
size(a) = (2,)
typeof(size(b)) = Tuple{Int64,Int64,Int64,Int64}
size(b) = (2,1,1,1)
Cint[size(b)...] = Int32[2,1]
```

i.e. if size(b) has more than 2 elements, only the first two show up in the result of Cint[size(b)...]!

**Comment by timholy** [comment]
Failure in constant-propagation before inference, https://github.com/JuliaLang/julia/issues/5560. Might be worth reporting there as an interesting example.
