### ISSUE TITLE
Failed to install CUDArt on Windows 7

### ISSUE THREAD

**Issue by liugengdai** [JuliaGPU/CUDArt.jl#44]
I have Julia 0.4.1 and CUDA 6.5 installed on my PC.
When I tried to install CUDArt.jl, I got the following erros:

        nvcc --shared --compiler-options="/wd4819" --linker-options= wrapcuda.c
-o libwrapcuda.dll
Internal error
NMAKE : fatal error U1077: '"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\
v6.5\bin\nvcc.EXE"' : return code '0xc0000005'
Stop.
===============================[ ERROR: CUDArt ]================================

LoadError: failed process: Process(`cmd /C 'C:\Program Files (x86)\Microsoft Vis
ual Studio 12.0\Common7\Tools\..\..\VC\vcvarsall.bat' amd64 & nmake -f Windows.m
k`, ProcessExited(2)) [2]
while loading C:\Users\liu\.julia\v0.4\CUDArt\deps\build.jl, in expression start
ing on line 23

===============================================================================

If anyone had the same problem? or any help from you?
Thank you so much.

Gengdai

**Comment by timholy** [comment]
I'm no help when it comes to Windows, but it looks like it can't find some Visual Studio file. If I were you, I'd start poking around [this file](https://github.com/JuliaGPU/CUDArt.jl/blob/master/deps/build.jl).

**Comment by liugengdai** [comment]
@timholy I tried many times. I don't know what I have changed but now it works. Probably I didn't set environment variables for CUDA properly. Thank you so much for your quick reply.

**Comment by timholy** [comment]
Glad you fixed it.
