### ISSUE TITLE
[Question] Can one allocate the shared memory using CUDArt.jl?

### ISSUE THREAD

**Issue by joaquimg** [JuliaGPU/CUDArt.jl#45]
Is it possible to allocate the shared memory or everything is done automatically always?
thanks in advance.

**Comment by timholy** [comment]
I'm not sure what you mean. If you use the commands in [this section](https://github.com/JuliaGPU/CUDArt.jl#device-arrays), you're explicitly allocating memory on the device. What kind of "sharing" did you have in mind? Do you know about SharedArrays? (They're on the CPU.)

**Comment by joaquimg** [comment]
I wanted to mean the memory dynamic shared memory between threads of some block. Like in the section dynamic shared memory [here](https://devblogs.nvidia.com/parallelforall/using-shared-memory-cuda-cc/)
The third field in:
```yourFunction<<<1, n, n*sizeof(int)>>>(d_d, n);```

used for sum reductions for instance.

I am aware of SharedArrays in CPU case.

**Comment by timholy** [comment]
Oh, right, now I remember this kind of thing. Honestly, I don't remember (it's been at least a year since I put a lot of effort into this package), this is probably the kind of thing you'll have to dig into the source code for. If it's not supported, a PR implementing it would be great!

**Comment by adambrewster** [comment]
Yes.

When calling launch (```function launch(f::CuFunction, grid::CudaDims, block::CudaDims, args::Tuple; shmem_bytes::Int=4, stream=null_stream)```,  set ```shmem_bytes``` to the desired size.

**Comment by maleadt** [comment]
This functionality is covered by CUDAdrv's `cudacall` nowadays, which accepts a keyword argument `shmem` to specify the bytes of shared memory to dynamically allocate.

I'll update the README and examples, which apparently are still using `launch`.
