### ISSUE TITLE
Gsoc proposal

### ISSUE THREAD

**Issue by NaelsonDouglas** [JuliaGPU/CUDArt.jl#46]
Hello,

I intend to apply to Google Summer of Code by using the idea [Writing high-performance, multithreaded kernels for image processing](http://julialang.org/soc/ideas-page.html#writing-high-performance-multithreaded-kernels-for-image-processing) and my  proposal, will use CUDArt.jl to improve the parallel image processing performance.

I'm writing here to ask for some feedback on what should I know first about CUDArt.jl to start working on my project or if you guys could help me on pointing how I can improve the idea.

This is  [my project proposal](https://docs.google.com/document/d/1h0mw4L8Ixx9ED_LincbJtqCTfQ5MrhN3j4FoeY_2mqM/edit?usp=sharing), feel free to have a look and comment on the dock or here in the thread.

Thanks.

Naelson Douglas

**Comment by timholy** [comment]
Hi @NaelsonDouglas. Thanks for your interest! I've taken a glance at your proposal. The main thing would be to flesh it out with some more specifics. Which algorithms will you tackle? How would you leverage CUDArt? Are the kernels written in julia, C/C++, or some combination? Can you break the tasks down into steps? What kind of milestones do you envision?

**Comment by NaelsonDouglas** [comment]
Thanks @timholy,

I'm taking note of your observations and editing the doc based on them. Since the deadline is  almost now, I'm going to write in the doc first and then I can answer here. 
I appreciate your attention.

Naelson Douglas
