### ISSUE TITLE
Can CUDArt be loaded with VS2015?

### ISSUE THREAD

**Issue by liusihaoshiwo** [JuliaGPU/CUDArt.jl#48]
I have the following problem when I try to add CUDArt.

I have already installed VS2015. But it seems that I should install VS2013,2012 or 2010. I want to know if it necessary for me to install another version of Visual Studio. If not, what should I do?

Pkg.add("CUDArt")
INFO: Cloning cache of CUDArt from git://github.com/JuliaGPU/CUDArt.jl.git
INFO: Installing CUDArt v0.2.3
INFO: Building CUDArt
===============================[ ERROR: CUDArt ]================================

LoadError: Cannot find proper Visual Studio installation. VS 2013, 2012, or 2010 is required.
while loading C:\Users\Miller\.julia\v0.4\CUDArt\deps\build.jl, in expression starting on line 10

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDArt had build errors.

 - packages with build errors remain installed in C:\Users\Miller\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("CUDArt")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

**Comment by timholy** [comment]
I don't know much about Windows, so others may have to help you if you can't figure this out. But check out the `build.jl` script as listed in the backtrace; presumably it's just a matter of adding a check for a newer version of VS.

Assuming you do this in a way that doesn't break things for other users, please [submit your fix as a pull request](http://docs.julialang.org/en/stable/manual/packages/#package-development)!

**Comment by liusihaoshiwo** [comment]
@timholy yeah.. I guess so. But I don't know what check should I add in my VS. I will continue trying.

**Comment by timholy** [comment]
I don't think you need to change your VS in any way, this seems to be an environment variable and/or path issue.

Before trying to load CUDArt you can do this: 
```jl
julia> ENV["foo"] = "bar"
"bar"

julia> haskey(ENV, "foo")
true
```
So you could spoof having VS 2012 (VS120COMNTOOLS) until you figure out the magic incantation.

**Comment by musmo** [comment]
@liusihaoshiwo Did you get this to work? I think the problem is that CUDA 7.5 doesn't even properly work with VS 2015, thus I don't see why you would expect this to build too

```julia
julia> Pkg.build("CUDArt")
INFO: Building CUDArt

Microsoft (R) Program Maintenance Utility Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        nvcc --shared --compiler-options="/wd4819" --linker-options= wrapcuda.c -o libwrapcuda.dll
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported
NMAKE : fatal error U1077: '"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.EXE"' : return code '0x1'
Stop.
========================================================[ ERROR: CUDArt ]========================================================


LoadError: failed process: Process(`cmd /C 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcvarsall.bat' amd64 & nmake -f Windows.mk`, ProcessExited(2)) [2]
while loading C:\Users\Mustafa\.julia\v0.5\CUDArt\deps\build.jl, in expression starting on line 23

=================================================================================================================================


========================================================[ BUILD ERRORS ]=========================================================


WARNING: CUDArt had build errors.

 - packages with build errors remain installed in C:\Users\Mustafa\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("CUDArt")`
 - build a single package by running its `deps/build.jl` script

==================================================================================================
```

**Comment by ChrisRackauckas** [comment]
Yes, VS2015 has issues with CUDA 7.5 that would be hard to get around. CUDA 8 solves those issues, so CUDArt.jl should work pretty much out of the box with VS2015 once CUDA 8 is out.

**Comment by kshyatt** [comment]
CUDA 8 is out. Does VS2015 work with this package now? Can we add that line to `build.jl`? What about VS14?

**Comment by musm** [comment]
@kshyatt finally VS2015 support for cuda:  https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/

**Comment by kshyatt** [comment]
Yes, but has anyone actually built this package with it?

**Comment by ChrisRackauckas** [comment]
I've been using it for awhile (since I got a GTX 1080). It works. Never tried it with VS though.

**Comment by kshyatt** [comment]
I can certainly believe CUDA 8 works and this package works with `gcc` and CUDA 8. But the issue is about VS :). Can someone try it out?

**Comment by musm** [comment]
I can confirm this works if add VS140COMNTOOLS
https://github.com/JuliaGPU/CUDArt.jl/blob/master/deps/build.jl#L3
yayy

Sans the slew of deprecation warnings

**Comment by kshyatt** [comment]
Thanks for checking! Do you mind opening a PR (and maybe fixing some depwarns?)

**Comment by musm** [comment]
Also tests don't pass but that's another thing.

**Comment by musm** [comment]
Troublesome test:


ERROR: MethodError: no method matching copy!(::CUDArt.CudaArray{Float64,2}, ::Array{Float32,2})
Closest candidates are:
  copy!{T}(::Array{T,N}, ::Array{T,N}) at array.jl:68
  copy!(::BitArray{N}, ::Array{T,N}) at bitarray.jl:457
  copy!(::Base.PermutedDimsArrays.PermutedDimsArray{T,N,perm,iperm,AA<:AbstractArray}, ::AbstractArray{T,N}) at permuteddimsarray.jl:62

**Comment by musm** [comment]
hopefully Tim can update the package with the pr for this fix

**Comment by timholy** [comment]
Not sure which PR you mean?

With all the work on Images and the zoo of associated changes to arrays/colors/numbers/io, GPUs are just beyond me to think about right now. I'm happy to allow others to make decisions here. It's not like I'm a huge expert on the subject, anyway (there are many who know much more). Perhaps the pool of contributors should be enlarged if we're missing people who know stuff who can merge things.

**Comment by musm** [comment]
ah sorry I meant TIm @maleadt  : )

**Comment by maleadt** [comment]
@musm I'm not a Windows user, and CUDArt's tests aren't failing on my setup (Linux x64, Julia nightly, CUDA 8) -- except occasionally for the `gc()` ones which are just fragile. Maybe make a separate bug report with some more information and a full backtrace (the one you posted doesn't show which test failed)?

**Comment by musm** [comment]
#59

**Comment by musm** [comment]
can be now closed

**Comment by kshyatt** [comment]
Thanks for all your work on this @musm!
