### ISSUE TITLE
ERROR: unknown package CUDArt

### ISSUE THREAD

**Issue by xximranxx** [JuliaGPU/CUDArt.jl#5]
Hi,

Pkg.add("CUDArt") gives me:
ERROR: unknown package CUDArt

hope I am missing something trivial

thanks

**Comment by timholy** [comment]
I guess I've never registered it. Until I get to that, you should be able to use `Pkg.clone` to install it.

**Comment by malmaud** [comment]
This can probably be closed now?

**Comment by timholy** [comment]
Yup. Thanks.
