### ISSUE TITLE
Cannot find CUDA runtime API in Ubuntu 14.04, CUDA 6.5

### ISSUE THREAD

**Issue by moon6pence** [JuliaGPU/CUDArt.jl#7]
Before send PR, I tested the code in my linux system. 
But even in master branch, I got error that cannot find cuda runtime api. 

I had to update the location of `libcudart` as below commit: `/usr/local/cuda` -> `/usr/local/cuda/lib64`

https://github.com/moon6pence/CUDArt.jl/commit/923e05c4a6559d6ec836935ff5c57f90be701301

`libcuda` has no problem to load, but I update the location that really it is.

**Comment by timholy** [comment]
On my machine, it looks like that directory got added to my `/etc/ld.so.conf`. So in fact I could delete all the suggested search directories and it still loaded fine. For me, `libcuda.so` is under `/usr/local/cuda/lib64/stubs`.

Feel free to include appropriate library path changes as part of your PR (or as two separate PRs if you prefer).
