### ISSUE TITLE
Makefile needs to select correct gcc compiler

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDArt.jl#72]
Plainly invoking `nvcc` isn't guaranteed to work:

```
nvcc -ptx -gencode=arch=compute_20,code=sm_20 utils.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /opt/cuda/bin/..//include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/opt/cuda/bin/..//include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
Makefile:15: recipe for target 'utils.ptx' failed
make: *** [utils.ptx] Error 1
```

Luckily, I've already implemented such a mechanism as part of [CUDAdrv](https://github.com/JuliaGPU/CUDAdrv.jl/blob/92a28dbb5c441adf4bf03926ab3cbada8d24e47c/examples/compilation/library.jl#L69-L177). Maybe we should move this functionality, and the entire compilation example, over to CUDArt (since CUDAdrv doesn't require `nvcc` to be installed except for that example)?

**Comment by musm** [comment]
I guess this is noe fixed
