### ISSUE TITLE
gcc5.4.0 support

### ISSUE THREAD

**Issue by ziyixi** [JuliaGPU/CUDArt.jl#90]
Hello, I am using ubuntu 16.04 and the gcc version is 5.4.0. I find that cuda v8.0.61 has removed the limit of gcc version no more than 5.3, so I changed build.jl, line 154 to (v"8.0", v"5.4.0"). I think it makes sense so ubuntu users can make use of your masterpiece. Thanks a lot!

**Comment by maleadt** [comment]
Should be fixed, please verify. Only properly fixed for CUDA 7.5 and 8.0, if you want to support an older CUDA please post the contents of its `host_config.h`.
