### ISSUE TITLE
GCC Version On CUDA 8.0

### ISSUE THREAD

**Issue by JMurph2015** [JuliaGPU/CUDArt.jl#98]
Hi!
So the max version that this package's build script will allow for gcc on CUDA 8.0 is 5.3.1.  However, even Xenial has moved on with gcc-5 up to 5.4.0 at least.  [https://packages.ubuntu.com/xenial/gcc-5](https://packages.ubuntu.com/xenial/gcc-5)  This makes it impossible to build on anything newer than a slightly out of date 16.04 machine without hacking the build.jl.  I use 17.04, so for me it's just flat out ridiculous to get anything older than 5.4.1 (which works fine with CUDA).

I propose bumping the build.jl requirement from 5.3.1 to 5.4.1.  Thanks!

**Comment by Keno** [comment]
This seems to be fixed on master already. @maleadt tag a new version?

**Comment by JMurph2015** [comment]
@Keno Good catch, I hadn't actually checked master, just the build script coming from Julia's install.  A new tag would be much appreciated.

**Comment by maleadt** [comment]
Yeah, sorry, forgot about tagging a new version. There's been plenty changes in CUDAdrv though, so I'll first do a more thorough check later today.
